# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "현우의 기록장"
description: > # this means to ignore newlines until "email:"
   

email: hyeunwoo.jang@gmail.com
#blog logo
logo: "/assets/images/woo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: '장현우'
author: '장현우'
author_image: "/assets/images/woo.jpg"

paginate:	5

url: "https://aswooo.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/aswooo
    desc:	
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
